### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by hassanrazakhalid** [chnbohwr/wi_angular_admin#1]
Hello i am trying to do.  npm install but im getting error
<img width="585" alt="screen shot 2018-02-08 at 2 10 21 pm" src="https://user-images.githubusercontent.com/15266641/35964596-05b7d416-0cda-11e8-94cb-93156d8d2a1c.png">
. And the log file
[2018-02-08T09_08_53_858Z-debug.log](https://github.com/chnbohwr/wi_angular_admin/files/1706367/2018-02-08T09_08_53_858Z-debug.log)

**Comment by chnbohwr** [comment]
hi , try install npm instead sudo command.
manage your npm version by [nvm](https://github.com/creationix/nvm)
and reinstall dependency again, it will be fine.

![image](https://user-images.githubusercontent.com/6761222/35971529-459af0ac-0d09-11e8-85ea-3ebd757c8e18.png)
